apiVersion: apps/v1
kind: Deployment
metadata:
  name: truyumclientapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: TruyumClientApp
  template:
    metadata:
      labels:
        app: TruyumClientApp
    spec:
      containers:
      - name: truyumclientrepos
        image: truyumcr.azurecr.io/truyumclientrepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: dsconfigsn

---
apiVersion: v1
kind: Service
metadata:
  name: truyumclientapp
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: TruyumClientApp